### ISSUE TITLE
channel manager panix

### ISSUE THREAD

**Issue by vincenzopalazzo** [vincenzopalazzo/lampo.rs#218]
I get the following panic while running https://github.com/vincenzopalazzo/lampo.rs/pull/216

```
2024-05-15T19:37:33.542Z INFO lampo_channel_manager listening on chain event on the channel manager. [lampod/src/ln/channel_manager.rs:134]
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', /home/vincent/.cargo/git/checkouts/rust-lightning-54338d485d58ba5b/4a28d1b/lightning-background-processor/src/lib.rs:906:43
```

**Comment by vincenzopalazzo** [comment]
More logs are

```
2024-05-18T17:35:25.475Z INFO lampod Starting lightning node version `0.0.1`. [lampod/src/lib.rs:245]
2024-05-18T17:35:25.475Z INFO lampo Stating onchaind. [lampod/src/lib.rs:271]
2024-05-18T17:35:25.475Z INFO jsonrpc starting server on /home/vincent/.lampo/signet/lampod.socket. [lampo-jsonrpc/src/lib.rs:201]
2024-05-18T17:35:25.475Z INFO lampo_bitcoind Starting bitcoind polling .... [lampo-bitcoind/src/lib.rs:422]
2024-05-18T17:35:25.475Z INFO lampo Starting channel manager. [lampod/src/lib.rs:273]
2024-05-18T17:35:25.475Z ERROR ldk lightning::chain::chainmonitor:794 ERROR Failed to update channel monitor: no such monitor registered. [lampod/src/utils/logger.rs:49]
thread '<unnamed>' panicked at 'ChannelManager generated a channel update for a channel that was not yet registered!', /home/vincent/.cargo/git/checkouts/rust-lightning-54338d485d58ba5b/4a28d1b/lightning/src/chain/chainmonitor.rs:800:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2024-05-18T17:35:25.504Z INFO ldk lightning::chain::chainmonitor:766 INFO Persistence of new ChannelMonitor for channel fe6040d8e05da18b3bfd72f39d3643cd0926aeb5086dcd0fd0449f6ecf9fdb73 completed. [lampod/src/utils/logger.rs:47]
2024-05-18T17:35:25.512Z INFO ldk lightning::chain::chainmonitor:766 INFO Persistence of new ChannelMonitor for channel b41fcb4a220a4e894bc5c66429169c3d19045b7a468351bc185e6ff673d29964 completed. [lampod/src/utils/logger.rs:47]
2024-05-18T17:35:25.517Z INFO ldk lightning::chain::chainmonitor:766 INFO Persistence of new ChannelMonitor for channel 1ff9d0324aee8b2d0aedb780668c7d37d34713b148c5acb5a5ac049879de2151 completed. [lampod/src/utils/logger.rs:47]
2024-05-18T17:35:25.521Z INFO ldk lightning::chain::chainmonitor:766 INFO Persistence of new ChannelMonitor for channel 039b8bf15d3303f0c03043c14aad16df24d47bc4bd9672daba08e6b62bb19199 completed. [lampod/src/utils/logger.rs:47]
2024-05-18T17:35:25.522Z INFO lampo Starting peer manager. [lampod/src/lib.rs:275]
2024-05-18T17:35:25.522Z INFO lampod-cli ------------ Starting Server ------------. [lampod-cli/src/main.rs:151]
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', /home/vincent/.cargo/git/checkouts/rust-lightning-54338d485d58ba5b/4a28d1b/lightning-background-processor/src/lib.rs:906:43
2024-05-18T17:35:25.522Z INFO lampo_channel_manager listening on chain event on the channel manager. [lampod/src/ln/channel_manager.rs:134]
2024-05-18T17:35:25.526Z INFO lampo Listening for in-bound connection on 127.0.0.1:39736. [lampod/src/ln/peer_manager.rs:143]
```
