### ISSUE TITLE
lnprototest: deadlock found while running the lampo deamon

### ISSUE THREAD

**Issue by vincenzopalazzo** [vincenzopalazzo/lampo.rs#226]
```
    raise EventError(self, "{}: message was {}".format(err, msg.to_str()))
lnprototest.errors.EventError: `open_channel.channel_flags: 0 != 1: message was open_channel chain_hash=06226e46111a0b59caaf126043eb5bbf28c34f3a5e332a1fc7b2b73cf188910f temporary_channel_id=0b534f316a7237975b1e73556273dcb26d115d8d721481d141b1e5fa54b1a6b5 funding_satoshis=999877 push_msat=0 dust_limit_satoshis=354 max_htlc_value_in_flight_msat=99987700 channel_reserve_satoshis=9998 htlc_minimum_msat=1 feerate_per_kw=253 to_self_delay=144 max_accepted_htlcs=50 funding_pubkey=03e60fce93b59e9ec53011aabc21c23e97b2a31369b87a5ae9c44ee89e2a6dec0a revocation_basepoint=03defdea4cdb677750a420fee807eacf21eb9898ae79b9768766e4faa04a2d4a34 payment_basepoint=025601570cb47f238d2b0286db4a990fa0f3ba28d1a319f5e7cf55c2a2444da7cc delayed_payment_basepoint=022b4ea0a797a443d293ef5cff444f4979f06acfebd7e86d277475656138385b6c htlc_basepoint=024ce119c96e2fa357200b559b2f7dd5a5f02d5290aff74b03f3e471b273211c97 first_per_commitment_point=0288a618cb6027c3218a37cbe9e882379f17d87d03f6e99d0b60292478d2aded06 channel_flags=0 tlvs={upfront_shutdown_script={shutdown_scriptpubkey=00148f80928cf2ce771e67ecfcc8d910afc5504fbc8c},channel_type={type=1000}}` on event [{"event": "ExpectMsg", "file": "test_bolt2-01-open_channel.py", "pos": "194"},]
=========================================================================================================================================================== short test summary info ============================================================================================================================================================
FAILED tests/test_bolt2-01-open_channel.py::test_open_channel_opener_side - AssertionError: `open_channel.channel_flags: 0 != 1: message was open_channel chain_hash=06226e46111a0b59caaf126043eb5bbf28c34f3a5e332a1fc7b2b73cf188910f temporary_channel_id=0b534f316a7237975b1e73556273dcb26d115d8d721481d141b1e5fa54b1a6b5 funding_satoshis=...
======================================================================================================================================================= 1 failed, 5 deselected in 5.70s ========================================================================================================================================================
^CException ignored in: <module 'threading' from '/usr/lib/python3.12/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1592, in _shutdown
    atexit_call()
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 31, in _python_exit
    t.join()
  File "/usr/lib/python3.12/threading.py", line 1147, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.12/threading.py", line 1167, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt: 
make: *** [Makefile:11: check] Error 1
```

**Comment by vincenzopalazzo** [comment]
Merged in next https://github.com/vincenzopalazzo/lampo.rs/pull/227
